openapi: 3.0.3
info:
  title: Pareto API - Transactions
  version: 1.18.0
  description: Tracks all protocol-level actions including deposits, claims, and redemptions.

servers:
  - url: https://api.pareto.credit/v1

tags:
  - name: Transactions
    description: Protocol and user-level actions recorded on-chain

paths:
  /transactions:
    get:
      summary: List all transactions
      tags: [Transactions]
      parameters:
        - name: type
          in: query
          schema: { type: string }
        - name: status
          in: query
          schema: { type: string }
        - name: walletAddress
          in: query
          schema: { type: string }
        - name: vaultId
          in: query
          schema: { type: string }
        - name: chainId
          in: query
          schema: { type: string }
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  totalCount:
                    type: integer

components:
  schemas:
    Transaction:
      type: object
      required:
        - _id
        - type
        - status
        - hash
        - chainId
        - walletAddress
        - vaultId
        - epochId
        - tokenId
        - amount
        - amountUSD
        - gasFeeUSD
        - block
        - createdAt
        - updatedAt
        - createdBy
        - updatedBy
      properties:
        _id: { type: string }
        type:
          type: string
          enum: [DEPOSIT, REDEEM, CLAIM]
        status:
          type: string
          enum: [PENDING, SUCCESS, FAILED]
        hash: { type: string }
        chainId: { type: string }
        walletAddress: { type: string }
        vaultId: { type: string }
        epochId: { type: string }
        tokenId: { type: string }
        amount: { type: string }
        amountUSD: { type: string }
        gasFeeUSD: { type: string }
        block:
          type: object
          properties:
            number: { type: number }
            timestamp: { type: number }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        createdBy: { type: string }
        updatedBy: { type: string }