openapi: 3.0.3
info:
  title: Pareto API - Vault Latest Blocks
  version: 1.18.0
  description: Real-time data snapshots of the latest on-chain state for each vault.

servers:
  - url: https://api.pareto.credit/v1

tags:
  - name: Vault Latest Blocks
    description: Live blockchain state snapshots for vaults

paths:
  /vault-latest-blocks:
    get:
      summary: List the latest block snapshot per vault
      tags: [Vault Latest Blocks]
      responses:
        '200':
          description: Latest vault state per block
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VaultLatestBlock'
                  totalCount:
                    type: integer

components:
  schemas:
    VaultLatestBlock:
      type: object
      required:
        - vaultId
        - vaultAddress
        - block
        - TVL
        - price
        - APRs
        - createdAt
        - updatedAt
        - createdBy
        - updatedBy
      properties:
        vaultId: { type: string }
        vaultAddress: { type: string }
        block:
          type: object
          properties:
            number: { type: number }
            timestamp: { type: number }
        TVL:
          type: object
          properties:
            token: { type: string }
            USD: { type: string }
        price: { type: string }
        APRs:
          type: object
          properties:
            BASE: { type: number }
            HARVEST: { type: number }
            REWARDS: { type: number }
            GROSS: { type: number }
            NET: { type: number }
            FEE: { type: number }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        createdBy: { type: string }
        updatedBy: { type: string }